// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject;

namespace SimpleSong.Migrations
{
    [DbContext(typeof(SimpleSongContext))]
    [Migration("20211004105825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleSong.Model.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            AlbumName = "Na legalu",
                            Author = "Rychu Peja",
                            Length = 3.2000000000000002,
                            Title = "Jest jedna rzecz"
                        },
                        new
                        {
                            SongId = 2,
                            AlbumName = "Tabasko",
                            Author = "OSTR",
                            Length = 2.5,
                            Title = "Kochana Polsko"
                        },
                        new
                        {
                            SongId = 3,
                            AlbumName = "Najwieksze przeboje",
                            Author = "Krzysztof Krawczyk",
                            Length = 3.4500000000000002,
                            Title = "Chcialem Byc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
